version: "1"
services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: mern-ui
    networks:
      - mern-stack-net
    volumes:
      - ./ui/src:/usr/app/src
      - ./ui/public:/usr/app/public
    depends_on:
      - api
    stdin_open: true
    tty: true

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3080:3080
    container_name: mern-api
    networks:
      - mern-stack-net
    volumes:
      - ./api/src:/usr/app/src
networks:
  mern-stack-net:
    driver: bridge
